# -*- coding: utf-8 -*-
"""2webScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEa20KTDWYobZ-TBdoAGvpSuCtuJl1KR

##web scrapping
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

webpage =  requests.get('https://quotes.toscrape.com')
soup = BeautifulSoup(webpage.text, 'lxml')
print(soup.prettify())

#gives the hlml code of the website

soup.find_all('h1')[0].text  #prints all h1 tags

for i in soup.find_all('span', class_='text'):
  print(i.text)











